libary

In [2]:
import numpy as ny

In [14]:
b =ny.array([(1,2,3),(4,5,0)])

In [ ]:
print(b)

In [ ]:
trans=ny.transpose(b)

In [ ]:
print(trans)

In [ ]:
trans.ravel()

In [ ]:
b.reshape(3,2)

In [11]:
zero=ny.ones((5,5))

In [9]:
print(zero)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
ny.random.random((2,2))

array([[0.32086053, 0.47970553],
       [0.0285099 , 0.57239349]])

In [15]:
zero=ny.delete(b,3)

In [16]:
print(zero)

[1 2 3 5 0]


In [18]:
zero=ny.insert(b,2,4)

In [19]:
print(zero)

[1 2 4 3 4 5 0]
